### ISSUE TITLE
Update Pressing Thumbs info

### ISSUE THREAD

**Issue by wilk10** [Vrixyz/bevy_awesome_prod#3]
Thanks for keeping this list. I have recently announced `"Times of Progress"`, it's listed as `PressingThumbs` in the readme (it's the name of my company). Can you please update it as `"Times of Progress - A City Builder set during the Industrial Revolution"` (or any description you prefer) and link to its Steam page? https://store.steampowered.com/app/2628450/Times_of_Progress/

I'm happy to open a PR if you prefer.

**Comment by Vrixyz** [comment]
Sure thing! I look forward to your progress 👍
